language: go

go:
  - 1.6

services:
  - mysql

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get github.com/golang/lint/golint
  - go get -v -d


before_script:
  - printf "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - printf -- "-----BEGIN RSA PRIVATE KEY-----\n${git_ssh}-----END RSA PRIVATE KEY-----\n" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - eval `ssh-agent -s`
  - ssh-add ~/.ssh/id_rsa
  - export PATH=$PATH:$GOPATH/bin
  - export OPENSHIFT_MYSQL_DB_HOST=127.0.0.1
  - export OPENSHIFT_MYSQL_DB_PORT=3306
  - export OPENSHIFT_MYSQL_DB_USERNAME=root
  - export OPENSHIFT_MYSQL_DB_NAME=domainglass
  - export OPENSHIFT_MYSQL_DB_PASSWORD=""

script:
  - make deploy coveralls