language: go

go:
  - 1.6

services:
  - mysql

before_script:
  - git clone https://github.com/brimstone/projectbuilder.git projectbuilder
  - export PROJECTBUILDER="$PWD/projectbuilder"
  - printf "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - eval `ssh-agent -s`
  - ssh-add ~/.travis/id_rsa
  - export PATH=$PATH:$GOPATH/bin
  - export OPENSHIFT_MYSQL_DB_HOST=127.0.0.1
  - export OPENSHIFT_MYSQL_DB_PORT=3306
  - export OPENSHIFT_MYSQL_DB_USERNAME=root
  - export OPENSHIFT_MYSQL_DB_NAME=domainglass
  - export OPENSHIFT_MYSQL_DB_PASSWORD=""
  - mysql -uroot -e 'create database domainglass'

script:
  - make travis
